site_name: Security Policies and Standards
site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs: false
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  # palette:
  #   scheme: slate
  #   primary: teal
  #   accent: lime
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Switch to light mode
plugins:
  - search
  - social
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tevfair
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tevinf/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
nav:
  - Home: index.md
  - Security Policies:
      - Access Control and Authorization Policy: Access_Control_and_Authorization_Policy.md
      - Audit and Monitoring Policy: Audit_and_Monitoring_Policy.md
      - Data Security Policy: Data_Security_Policy.md
      - Development and DevOps Policy: Development_and_DevOps_Policy.md
      - DR Backup Policy: DR_Backup_Policy.md
      - IAM Policy: IAM_Policy.md
      - Incident Response and Management Policy: Incident_Response_and_Management_Policy.md
      - Key Management Security Policy: Key_Management_Security_Policy.md
      - Network Security Policy: Network_Security_Policy.md
      - Vulnerability Management Policy: Vulnerability_Management_Policy.md
  - Security Standards:
      - Access Control and Authorization Policy: Access_Control_and_Authorization_STANDARD_300.md
      - Audit and Monitoring Standard: Audit_and_Monitoring_Standard_400.md
      - Backup and Recovery Standard: Backup_and_Recovery_Standard_100.md
      - Data Security Standard: Data_Security_Standard_200.md
      - Development and DevOps Standard: Development_and_DevOps_Standard_800.md
      - IAM STANDARD: IAM_STANDARD_1000.md
      - Incident Response and Management Standard: Incident_Response_and_Management_Standard_500.md
      - Key Management Standard: Key_Management_Standard_600.md
      - Network Security Standard: Network_Security_Standard_700.md
      - Vulnerability Management Standard: Vulnerability_Management_Standard_900.md

copyright: |
  &copy; 2024 <a href="https://github.com/tevfair" target="_blank" rel="noopener">Tevin Fair</a>
